version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    labels:
      - "traefik.http.routers.db.rule=Host(`db.cra.local`)"